# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    # - gripper_controller

  arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Revolute 7
      - Revolute 8
      - Revolute 9
      - Revolute 10
      - Revolute 11
 
   
  # gripper_controller:
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: True
  #   joints:
  #     - joint_6
  #     - joint_7
    
    